import os
import re
from collections import OrderedDict

import openpyxl

EXCEL_DIR = r"C:\Users\MT\Desktop\pms"
OUTPUT_SQL = r"C:\Users\MT\Desktop\pms\pms-website\seed\seed_data.sql"

TEMPLATE_MAP = OrderedDict([
    ("AIR COMPRESSOR", "Air Compressor"),
    ("AIR WINCH", "Air Winch"),
    ("CENTRIFUGAL PUMP", "Centrifugal Pump"),
    ("HYDRAULIC WINCH", "Hydraulic Winch"),
    ("MAN RIDER", "Man Rider Winch"),
    ("MUD AGITATOR", "Mud Agitator"),
])

COMMON_AR = {
    "COMPLETE REQUIRED PERMIT-TO-WORK (PTW).RECORD AT THE NOTIFICATION THE PTW NUMBER.":
        "إكمال تصريح العمل المطلوب (PTW)",
    "MECHANICAL AND ELECTRICAL LOCKOUT / TAG-OUT PERMIT REQUIRED.":
        "قفل / وضع علامة ميكانيكية وكهربائية مطلوب",
    "REVIEW / COMPLETE JOB-SAFETY-ANALYSIS (JSA).":
        "مراجعة / إكمال تحليل سلامة الوظيفة (JSA)",
    "INFORM AREA AUTHORITY IF WORK IS CARRIED OUT ON CRITICAL EQUIPMENT FOR ONGOING OPERATION.":
        "إبلاغ سلطة المنطقة إذا تم العمل على معدات حيوية للعملية المستمرة",
    "WHERE APPROPRIATE, ENSURE TEST EQUIPMENT AND TOOLS HAVE VALID CERTIFICATION/CALIBRATION":
        "التأكد من أن معدات وأدوات الاختبار لديها شهادة/معايرة سارية",
    "WEAR ALL PROPER SAFETY EQUIPMENT":
        "ارتداء جميع معدات السلامة المناسبة",
}

GENERIC_TASK_TERMS = {
    "CHECK": "فحص",
    "INSPECT": "تفتيش",
    "CLEAN": "تنظيف",
    "TEST": "اختبار",
    "CHANGE": "تغيير",
    "REPLACE": "استبدال",
    "LUBRICATE": "تزييت",
    "RECORD": "تسجيل",
    "ENSURE": "التأكد",
    "FUNCTION TEST": "اختبار وظيفي",
    "VISUALLY INSPECT": "فحص بصري",
    "APPLY": "وضع",
    "MANUALLY": "يدويًا",
}


def sql_escape(val):
    if val is None:
        return "NULL"
    s = str(val).replace("'", "''")
    return f"'{s}'"


def arabic_fallback(task_en):
    if task_en in COMMON_AR:
        return COMMON_AR[task_en]
    for eng_word, ar_word in GENERIC_TASK_TERMS.items():
        if task_en.strip().upper().startswith(eng_word):
            rest = task_en.strip()[len(eng_word):].strip().rstrip(".")
            return f"{ar_word} {rest}"
    return task_en


def detect_template(filename):
    upper = filename.upper()
    for key, name in TEMPLATE_MAP.items():
        if key in upper:
            return name
    return "Unknown"


def read_tasks(ws):
    tasks = []
    for r in range(22, 60):
        item = ws.cell(row=r, column=1).value
        desc = ws.cell(row=r, column=2).value
        if desc and isinstance(desc, str) and desc.strip():
            desc = desc.strip()
            if desc.upper().startswith("COMMENT") or desc.upper().startswith("BMS") or desc.upper().startswith("DO NOT SUBMIT") or desc.upper().startswith("MAKE SURE THAT") or desc.upper().startswith("REPORT ALL"):
                continue
            tasks.append(desc)
    return tasks


def main():
    all_files = sorted(f for f in os.listdir(EXCEL_DIR) if f.endswith(".xlsx") and not f.startswith("~$") and f != "PM_Analysis_Summary.xlsx")
    print(f"Found {len(all_files)} Excel files")

    template_name_to_id = {}
    for idx, (_, name) in enumerate(TEMPLATE_MAP.items(), start=1):
        template_name_to_id[name] = idx

    template_tasks_map = OrderedDict()
    template_arabic_map = OrderedDict()
    for _, name in TEMPLATE_MAP.items():
        template_tasks_map[name] = []

    all_equipment = []

    for fname in all_files:
        fpath = os.path.join(EXCEL_DIR, fname)
        tname = detect_template(fname)
        if tname == "Unknown":
            print(f"  SKIP (unknown template): {fname}")
            continue
        wb = openpyxl.load_workbook(fpath, data_only=True)
        ws = wb.active

        equipment_name = ws.cell(row=5, column=5).value or ""
        model = ws.cell(row=6, column=5).value or ""
        make = ws.cell(row=7, column=5).value or ""
        serial_number = ws.cell(row=6, column=16).value or ""

        all_equipment.append({
            "template_name": tname,
            "equipment_name": str(equipment_name).strip(),
            "model": str(model).strip(),
            "make": str(make).strip(),
            "serial_number": str(serial_number).strip(),
        })

        tasks = read_tasks(ws)
        existing = [t.lower() for t in template_tasks_map[tname]]
        for t in tasks:
            if t.lower() not in existing:
                template_tasks_map[tname].append(t)
                existing.append(t.lower())

        wb.close()

    for tname in template_tasks_map:
        template_arabic_map[tname] = [arabic_fallback(t) for t in template_tasks_map[tname]]

    lines = []
    lines.append("-- ============================================================")
    lines.append("-- PMS Seed Data")
    lines.append("-- Generated by import_templates.py")
    lines.append(f"-- Files processed: {len(all_files)}")
    lines.append("-- ============================================================")
    lines.append("")

    lines.append("-- ---------------------------------------------------")
    lines.append("-- Frequencies (from 0002_seed_frequencies.sql)")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO frequencies (id, name, name_ar, type, interval_days, interval_hours, sort_order) VALUES")
    freq_data = [
        (1, "Weekly", "أسبوعي", "calendar", 7, None, 1),
        (2, "Monthly", "شهري", "calendar", 30, None, 2),
        (3, "Quarterly", "ربع سنوي", "calendar", 90, None, 3),
        (4, "6 Months", "نصف سنوي", "calendar", 180, None, 4),
        (5, "1 Year", "سنوي", "calendar", 365, None, 5),
        (6, "500 Hours", "500 ساعة", "hourly", None, 500, 6),
        (7, "1000 Hours", "1000 ساعة", "hourly", None, 1000, 7),
        (8, "2000 Hours", "2000 ساعة", "hourly", None, 2000, 8),
        (9, "3000 Hours", "3000 ساعة", "hourly", None, 3000, 9),
        (10, "6000 Hours", "6000 ساعة", "hourly", None, 6000, 10),
        (11, "Custom", "مخصص", "custom", 0, 0, 99),
    ]
    freq_rows = []
    for (fid, name, name_ar, typ, idays, ihours, sorder) in freq_data:
        ihours_sql = "NULL" if ihours is None else str(ihours)
        idays_sql = "NULL" if idays is None else str(idays)
        freq_rows.append(f"  ({fid}, {sql_escape(name)}, {sql_escape(name_ar)}, {sql_escape(typ)}, {idays_sql}, {ihours_sql}, {sorder})")
    lines.append(",\n".join(freq_rows) + ";")
    lines.append("")

    lines.append("-- ---------------------------------------------------")
    lines.append("-- Templates")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO templates (id, name, name_ar, description) VALUES")
    template_names_ar = {
        "Air Compressor": "ضاغط هواء",
        "Air Winch": "ونش هواء",
        "Centrifugal Pump": "مضخة طرد مركزي",
        "Hydraulic Winch": "ونش هيدروليكي",
        "Man Rider Winch": "ونش نقل الأفراد",
        "Mud Agitator": "خلاط طين",
    }
    template_rows = []
    for idx, (_, tname) in enumerate(TEMPLATE_MAP.items(), start=1):
        desc_en = f"{tname} Monthly PM Checklist"
        desc_ar = f"قائمة الصيانة الشهرية لـ {template_names_ar[tname]}"
        template_rows.append(f"  ({idx}, {sql_escape(tname)}, {sql_escape(template_names_ar[tname])}, {sql_escape(desc_en)})")
    lines.append(",\n".join(template_rows) + ";")
    lines.append("")

    total_task_count = 0
    lines.append("-- ---------------------------------------------------")
    lines.append("-- Template Tasks")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO template_tasks (id, template_id, item_number, task_description, task_description_ar, sort_order) VALUES")
    all_task_rows = []
    task_id = 1
    for tidx, (_, tname) in enumerate(TEMPLATE_MAP.items(), start=1):
        tasks = template_tasks_map[tname]
        ar_tasks = template_arabic_map[tname]
        for i, (task_en, task_ar) in enumerate(zip(tasks, ar_tasks), start=1):
            all_task_rows.append(f"  ({task_id}, {tidx}, {i}, {sql_escape(task_en)}, {sql_escape(task_ar)}, {i})")
            task_id += 1
            total_task_count += 1
    lines.append(",\n".join(all_task_rows) + ";")
    lines.append(f"-- Total tasks: {total_task_count}")
    lines.append("")

    lines.append("-- ---------------------------------------------------")
    lines.append("-- Equipment")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO equipment (id, template_id, equipment_name, model, make, serial_number, location) VALUES")
    equip_rows = []
    for eidx, eq in enumerate(all_equipment, start=1):
        tid = template_name_to_id[eq["template_name"]]
        equip_rows.append(f"  ({eidx}, {tid}, {sql_escape(eq['equipment_name'])}, {sql_escape(eq['model'])}, {sql_escape(eq['make'])}, {sql_escape(eq['serial_number'])}, 'Rig 8')")
    lines.append(",\n".join(equip_rows) + ";")
    lines.append("")

    lines.append("-- ---------------------------------------------------")
    lines.append("-- Equipment Schedules (Monthly frequency for all)")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO equipment_schedules (equipment_id, frequency_id, is_active) VALUES")
    sched_rows = []
    for eidx in range(1, len(all_equipment) + 1):
        sched_rows.append(f"  ({eidx}, 2, 1)")
    lines.append(",\n".join(sched_rows) + ";")
    lines.append("")

    lines.append("-- ---------------------------------------------------")
    lines.append("-- Seed Admin / Manager User")
    lines.append("-- ---------------------------------------------------")
    lines.append("INSERT OR IGNORE INTO users (id, username, email, password_hash, role, full_name, preferred_lang)")
    lines.append("VALUES (1, 'manager', 'mohamedtarekhse@gmail.com', '$2a$10$initialhashplaceholder', 'manager', 'Mohamed Tarek', 'en');")
    lines.append("")

    os.makedirs(os.path.dirname(OUTPUT_SQL), exist_ok=True)
    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"SQL written to: {OUTPUT_SQL}")
    print(f"  Templates: {len(TEMPLATE_MAP)}")
    print(f"  Tasks: {total_task_count}")
    print(f"  Equipment: {len(all_equipment)}")
    print(f"  Schedules: {len(all_equipment)}")
    print(f"  Users: 1")


if __name__ == "__main__":
    main()
